tap "homebrew/bundle"
tap "homebrew/cask"
tap "sanemat/font"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "git"
brew "hugo"
brew "mas"
brew "openssl"
brew "watch"
brew "sanemat/font/ricty"
cask "alfred"
cask "caffeine"
cask "docker"
cask "firefox"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-japanese-ime"
cask "maczip4win"
cask "mysqlworkbench"
cask "skitch"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
cask "xquartz"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
